### ISSUE TITLE
Tests `TestGetBranch ` and `TestScanFS ` are racey

### ISSUE THREAD

**Issue by blkt** [mindersec/minder#5084] opened 2024-11-28 16:03 UTC
### Describe the issue

The following tests occasionally fail in CI

```
❌ TestGetBranch (0s)
❌ TestGetBranch/branch (0s)
      testing.go:1399: race detected during execution of test
❌ TestGetBranch/repo-default (0s)
      testing.go:1399: race detected during execution of test
❌ TestScanFS (0s)
      testing.go:1399: race detected during execution of test
```

### What version are you using?

85126cb

**Comment by puerco** [comment] 2024-11-29 03:55
Duplicate of https://github.com/mindersec/minder/issues/5075 should be fixed in in #5087

**Closed by puerco** 2024-11-29 03:55 UTC
Labels: bug
